---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: index.html
  label: Home
- type: document
  path: about.html
  label: About
- type: document
  path: pledge.html
  label: Pledge
- type: document
  path: news.html
  label: News
- type: document
  path: contact.html
  label: Contacts
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
upload_dir: assets/img
public_path: assets/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
