---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: release_year
  type: text
  config:
    required: false
  label: Release Year
  hidden: false
  description: This won't show up on the page. Use it to order the projects.
- name: highlight
  type: boolean
  label: Highlight
  description: Should this project be highlighted on the home page?
  default: false
- name: director
  type: textarea
  default: "<p></p>"
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Director
- name: writer
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Writer
- name: cast
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Cast
- name: produced
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Produced With
- name: synopsis
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Synopsis
- name: watch
  type: text
  config:
    required: false
  label: Watch
  description: 'Info about viewing platforms '
  hidden: true
- name: stills
  type: image_gallery
  config: {}
  label: Stills
- name: main_still
  type: file
  config:
    maxSize: 64
  label: Main Still
- name: image-align
  type: text
  config:
    required: false
  label: image-align
  hidden: true
- name: layout
  type: text
  config:
    required: false
  label: layout
  default: project
  hidden: true
pages:
- _projects/a-ciambra.html
- _projects/harriet.html
- _projects/hollywood-gold-a-stay-gold-podcast.html
- _projects/honey-boy.html
- _projects/joe-bell.html
- _projects/nanny.html
- _projects/patti-cake.html
- _projects/the-strange-ones.html
- _projects/together-together.html
- _projects/under-the-silver-lake.html
