---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: highlight
  type: boolean
  label: Highlight
  description: Should this project be highlighted on the home page?
  default: false
- name: director
  type: text
  config:
    required: false
  label: Director
- name: writer
  type: text
  config:
    required: false
  label: Writer
- name: cast
  type: text
  config:
    required: false
  label: Cast
- name: synopsis
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Synopsis
- name: watch
  type: text
  config:
    required: false
  label: Watch
  description: 'Info about viewing platforms '
- name: stills
  type: image_gallery
  config: {}
  label: Stills
- name: main_still
  type: file
  config:
    maxSize: 64
  label: Main Still
pages:
- _projects/a-ciambra.html
- _projects/harriet.html
- _projects/honey-boy.html
- _projects/joe-bell.html
- _projects/patti-cake.html
- _projects/the-strange-ones.html
- _projects/together-together.html
- _projects/under-the-silver-lake.html
